Sending statistics as a trace.
dbaghdasarya/wavefront-trace-loader pull request #26
Opened 2021-08-19 08:50 UTC by hrayrazizyan

2021-08-20 09:37 UTC, dbaghdasarya requested changes

2021-08-20 09:37 UTC, dbaghdasarya commented on src/main/java/com/wavefront/generators/FromPatternGenerator.java
> +    startGeneration(false, generatorConfig, LOGGER, "PATTERN");
I guess it will be better to define constant lines in Defaults.java to avoid typos in different parts of the code (I mean "PATTERN" and "TOPOLOGY").

2021-08-20 09:37 UTC, dbaghdasarya commented on src/main/java/com/wavefront/generators/TraceGenerator.java
> +    List<Pair<String, String>> list = new LinkedList<>();
Please add more info to the variable name. It is very easy to mix `list` and `list1`, but not `rootTags` and `traceTypeTags`.

2021-08-20 09:37 UTC, dbaghdasarya commented on src/main/java/com/wavefront/generators/TraceGenerator.java
> +        "localhost",
Please, replace `localhost` with `traceLoaderHost`.

2021-08-20 09:37 UTC, dbaghdasarya commented on src/main/java/com/wavefront/generators/TraceGenerator.java
> +      statTrace.add(0, type_stat);
`level = 0` only for the root span. Actually, this value doesn't matter in our case, but let's use the correct assigning.

2021-08-20 09:37 UTC, dbaghdasarya commented on src/main/java/com/wavefront/generators/FromTopologyGenerator.java
> +    startGeneration(false, generatorConfig, LOGGER, "TOPOLOGY");
The same is here.

2021-08-20 09:37 UTC, dbaghdasarya commented on src/main/java/com/wavefront/helpers/Statistics.java
> +
Extra empty lines.

2021-08-20 09:54 UTC, hrayrazizyan commented on src/main/java/com/wavefront/generators/TraceGenerator.java
> +      statTrace.add(0, type_stat);
Should I add both the root and trace types to level 1? If I put root to level 0 and trace types to level 1, the trace does not have the structure of a tree.

2021-08-23 07:00 UTC, dbaghdasarya approved these changes

2021-08-23 07:01 UTC, merged