hazizyan/MONIT-24455
dbaghdasarya/wavefront-trace-loader pull request #28
Opened 2021-08-25 12:07 UTC by hrayrazizyan

Added the possibility of sending statistics to a different server or customer from the other traces.
Added the possibility to turn on/off statistics reporting through direct ingestion.
Added root names to statistics traces
Added special symbols in front of statistics traces in case of printing to a file.

2021-08-25 14:09 UTC, dbaghdasarya requested changes

2021-08-25 14:09 UTC, dbaghdasarya commented on applicationConfig.yaml
> +#server: "meru.wavefront.com"
This is a public repo. Please, remove all sensitive data such as server name and token value.

2021-08-25 14:09 UTC, dbaghdasarya commented on src/main/java/com/wavefront/AbstractTraceLoader.java
> +      if(applicationConfig.getTraceOutputFile() != null){
This change is already in `master`. Did you rebase your branch on top of the latest master before pushing it?

2021-08-25 14:09 UTC, dbaghdasarya commented on src/main/java/com/wavefront/SpanSender.java
> +  private String reportStat = null;
Why `reportStat` is a string?

2021-08-25 14:09 UTC, dbaghdasarya commented on src/main/java/com/wavefront/SpanSender.java
> +        if(Defaults.STAT_ROOT_NAME_LIST.contains(tempTrace.getRoot())) {
As far as I remember this was discussed and considered to check span type instead of root span name.

2021-08-25 14:09 UTC, dbaghdasarya commented on src/main/java/com/wavefront/SpanSender.java
> +        StringBuilder stringBuilder = new StringBuilder("[{\"root\":\"" + tempTrace.getRoot() +
This operation is redundant in case of stat trace and `reportStat=false`.

2021-08-25 14:09 UTC, dbaghdasarya commented on src/main/java/com/wavefront/SpanSender.java
> +          if(tempSpan.getKind() == SpanKind.STATISTICS && reportStat != null){
I guess that here you have to check that `statSender!=null`.

2021-08-25 14:09 UTC, dbaghdasarya commented on src/main/java/com/wavefront/WavefrontTraceLoader.java
> +        statClientFactory.addClient("https://" + applicationConfig.getToken() +
What if a user uses `proxy` for ingestion and didn't provide a `serverName` and `token`?
I guess that `statSender` should be `null` in this case.

2021-08-25 14:09 UTC, dbaghdasarya commented on src/main/java/com/wavefront/config/ApplicationConfig.java
> +  private String reportStat = null;
I guess that Boolean is a more suitable type for this parameter.

2021-08-25 14:09 UTC, dbaghdasarya commented on src/main/java/com/wavefront/datastructures/Span.java
>      this.spanLogs = spanLogs;
Code duplication. You can here call the next constructor with `..., SpanKind.REGULAR` value.

2021-08-25 14:09 UTC, dbaghdasarya commented on src/main/java/com/wavefront/datastructures/StatSpan.java
> +  public StatSpan(String name, long startMillis, long durationMillis, @Nullable String source, UUID traceUUID, UUID spanUUID, @Nullable List<UUID> parents, @Nullable List<UUID> followsFrom, @Nullable
I guess that you don't need spanKind parameter for this constructor and can just set `SpanKind.STATISTICS` for the base class.

2021-08-25 14:09 UTC, dbaghdasarya commented on src/main/java/com/wavefront/datastructures/StatSpan.java
> +  public String toString() {
Do you use this overriding?

2021-08-25 14:09 UTC, dbaghdasarya commented on src/main/java/com/wavefront/generators/TraceGenerator.java
> +
Extra empty lines.

2021-08-25 14:09 UTC, dbaghdasarya commented on src/main/java/com/wavefront/generators/TraceGenerator.java
> +      StatSpan type_stat = new StatSpan(k,
We use `camelCase` for variables naming.

2021-08-25 14:09 UTC, dbaghdasarya commented on src/main/java/com/wavefront/generators/TraceGenerator.java
> +
Extra empty lines.

2021-08-25 14:09 UTC, dbaghdasarya commented on src/main/java/com/wavefront/generators/TraceGenerator.java
> +import com.wavefront.internal.reporter.WavefrontInternalReporter;
Do you really need all these new imports?

2021-08-25 14:09 UTC, dbaghdasarya commented on src/main/java/com/wavefront/helpers/Defaults.java
> +  public static final List<String> STAT_ROOT_NAME_LIST = List.of(
I guess that TraceTypePatternValidator should be updated to prohibit the usage of these words as a service name.

2021-08-25 15:50 UTC, hrayrazizyan commented on src/main/java/com/wavefront/SpanSender.java
> +  private String reportStat = null;
works fine with boolean

2021-08-25 15:50 UTC, hrayrazizyan commented on src/main/java/com/wavefront/config/ApplicationConfig.java
> +  private String reportStat = null;
works fine with boolean

2021-08-25 15:51 UTC, hrayrazizyan commented on src/main/java/com/wavefront/datastructures/StatSpan.java
> +  public String toString() {
for differentiating statistics spans from ordinary ones

2021-08-25 15:55 UTC, hrayrazizyan commented on src/main/java/com/wavefront/WavefrontTraceLoader.java
> +        statClientFactory.addClient("https://" + applicationConfig.getToken() +
So if neither server nor statServer have been provided, statistics will not be sent anywhere?

2021-08-25 16:01 UTC, hrayrazizyan commented on src/main/java/com/wavefront/SpanSender.java
> +        if(Defaults.STAT_ROOT_NAME_LIST.contains(tempTrace.getRoot())) {
Works fine with spanKind. Deleting STAT_ROOT_NAME_LIST from Defaults

2021-08-26 07:42 UTC, dbaghdasarya requested changes

2021-08-26 07:42 UTC, dbaghdasarya commented on src/main/java/com/wavefront/AbstractTraceLoader.java
> +
You haven't actually changed this file. Could you please revert it so it doesn't participate in the review?

2021-08-26 07:42 UTC, dbaghdasarya commented on src/main/java/com/wavefront/WavefrontTraceLoader.java
> +        statClientFactory.addClient("https://" + applicationConfig.getToken() +
Where to send it? 
If `reportStat=true` you can throw an exception and terminate the App. or just output it in console, like it was done before.

2021-08-26 07:42 UTC, dbaghdasarya commented on src/main/java/com/wavefront/WavefrontTraceLoader.java
> +        } else {
This if..if..else combination is complicated for understanding and checking. Please rework it.
BTW, what if `getServer()!=null` but `getToken()==null`?

2021-08-26 07:42 UTC, dbaghdasarya commented on src/main/java/com/wavefront/datastructures/Span.java
>      this.spanLogs = spanLogs;
I didn't mean to remove the previous constructor. It is a good practice to preserve methods signatures.
I asked you to replace the body with a call of the new constructor with the same parameters and additionally `kind=REGULAR`.

2021-08-26 07:42 UTC, dbaghdasarya commented on src/main/java/com/wavefront/generators/FromPatternGenerator.java
> +        SpanKind.REGULAR));
This should be updated when you rework the Span constructor.

2021-08-26 07:42 UTC, dbaghdasarya commented on src/main/java/com/wavefront/generators/FromPatternGenerator.java
> +              SpanKind.REGULAR));
The same is here.

2021-08-26 07:42 UTC, dbaghdasarya commented on src/main/java/com/wavefront/generators/FromTopologyGenerator.java
> +          SpanKind.REGULAR));
the same is here.

2021-08-26 07:42 UTC, dbaghdasarya commented on src/main/java/com/wavefront/generators/FromTopologyGenerator.java
> +              SpanKind.REGULAR));
The same is here.

2021-08-26 07:42 UTC, dbaghdasarya commented on src/main/java/com/wavefront/datastructures/SpanFromWF.java
> +        UUID.fromString(spanId), parents, followsFrom, tags, null, SpanKind.REGULAR);
Return the old constructor

2021-08-27 12:33 UTC, dbaghdasarya requested changes

2021-08-27 12:33 UTC, dbaghdasarya commented on src/main/java/com/wavefront/generators/FromPatternGenerator.java
> +import com.wavefront.datastructures.SpanKind;
Do you need to import SpanKind here?

2021-08-27 12:33 UTC, dbaghdasarya commented on src/main/java/com/wavefront/generators/FromTopologyGenerator.java
> +import com.wavefront.datastructures.SpanKind;
The same is here. (import SpanKind)

2021-08-27 12:33 UTC, dbaghdasarya commented on src/main/java/com/wavefront/generators/FromTopologyGenerator.java
> +        SpanKind.REGULAR));
Restore the call of the old constructor.

2021-08-27 12:33 UTC, dbaghdasarya commented on src/main/java/com/wavefront/generators/FromTopologyGenerator.java
> +            SpanKind.REGULAR));
The same is here.

2021-08-27 12:37 UTC, hrayrazizyan commented on src/main/java/com/wavefront/generators/FromTopologyGenerator.java
> +        SpanKind.REGULAR));
This fragment is already fixed.

2021-08-27 12:37 UTC, hrayrazizyan commented on src/main/java/com/wavefront/generators/FromTopologyGenerator.java
> +            SpanKind.REGULAR));
This fragment is already fixed.

2021-08-27 13:30 UTC, merged